name: Automated E2E Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build SASS
        run: npm run build

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Test Build End-To-End Tests
        run: npm run test-e2e-cli
        env:
          CYPRESS_EMAIL: ${{secrets.CYPRESS_EMAIL}}
          CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}
